package com.matheus.servermanager.database.model;

import com.matheus.servermanager.database.query.Insert;

public class ModelInsert<M extends DatabaseModel> {

	private final Table<M> table;
	private final Insert insert;
	private final M instance;

	public ModelInsert(Table<M> table, M instance) {
		this.table = table;
		this.insert = new Insert(table.getDatabase(), table.getName());
		this.instance = instance;
		this.insert.set(this.table.fromInstance(this.instance).getMap());
	}

	public M execute() {
		return this.table.applyAutoGenerated(this.instance, this.insert.execute());
	}
}
